function on_game_start()
    local medkits = axr_otheal.medkits
	
	if medkits then
		-- -- Faction Medkits
        medkits["medkit_faction_duty"] = true
        medkits["medkit_faction_bandit"] = true
        medkits["medkit_faction_freedom"] = true
        medkits["medkit_faction_merc"] = true
        medkits["medkit_faction_monolith"] = true
        medkits["medkit_faction_clearsky"] = true
        medkits["medkit_faction_sin"] = true
        medkits["medkit_faction_renegade"] = true
        medkits["medkit_faction_isg"] = true
    end
end