function on_game_start()
    local bandages = axr_otheal.bandages
    local medkits = axr_otheal.medkits
	
    if bandages then
		-- -- New Medkits and Bandages
        bandages["bandage_cooling"] = true
        bandages["bandage_presure"] = true
        bandages["bandage_rag"] = true
        bandages["bandage_bandaids"] = true
    end
	if medkits then
		-- -- New Medkits and Bandages
        medkits["medkit_civilian"] = true
        medkits["medkit_tactical"] = true
		-- -- Faction Medkits
        medkits["medkit_faction_duty"] = true
        medkits["medkit_faction_bandit"] = true
        medkits["medkit_faction_freedom"] = true
        medkits["medkit_faction_merc"] = true
        medkits["medkit_faction_monolith"] = true
        medkits["medkit_faction_clearsky"] = true
        medkits["medkit_faction_sin"] = true
        medkits["medkit_faction_renegade"] = true
        medkits["medkit_faction_isg"] = true
    end
	
	-- printf("ze table\n%s", utils_data.print_table(axr_otheal.bandages, false, true))
	-- printf("ze table\n%s", utils_data.print_table(axr_otheal.medkits, false, true))
	
end