function on_game_start()


	if TB_RF_Receiver_Packages.tb_extraloot then

		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"medkit_civilian","st_medkit_civilian"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"bandage_cooling","st_bandage_cooling"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"bandage_presure","st_bandage_presure"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_army, {"medkit_tactical","st_medkit_tactical"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_bandit, {"medkit_faction_bandit","st_medkit_faction_bandit"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_csky, {"medkit_faction_clearsky","st_medkit_faction_clearsky"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_dolg, {"medkit_faction_duty","st_medkit_faction_duty"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_dolg, {"medkit_tactical","st_medkit_tactical"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_ecolog, {"medkit_detox","st_medkit_detox"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_freedom, {"medkit_faction_freedom","st_medkit_faction_freedom"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_greh, {"medkit_faction_sin","st_medkit_faction_sin"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_isg, {"medkit_faction_isg","st_medkit_faction_isg"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_isg, {"medkit_combat","st_medkit_combat"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_killer, {"medkit_faction_merc","st_medkit_faction_merc"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_killer, {"medkit_combat","st_medkit_combat"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_monolith, {"medkit_faction_monolith","st_medkit_faction_monolith"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_renegade, {"medkit_faction_renegade","st_medkit_faction_renegade"} )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_stalker,  )
	
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.tb_extraloot, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_army, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_bandit, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_csky, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_dolg, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_ecolog, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_freedom, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_greh, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_isg, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_killer, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_monolith, false, true))
	-- printf("ze table\n%s", utils_data.print_table(TB_RF_Receiver_Packages.mc_faction_renegade, false, true))

	
	end
end



-- attempted to insert the new items as a whole new table, but for some reason the whole table is added as an element, not each separately:

		-- local tb_extraloot_list = {
			-- {"medkit_civilian","st_medkit_civilian"},
			-- {"bandage_cooling","st_bandage_cooling"},
			-- {"bandage_presure","st_bandage_presure"},
		-- }
		-- local mc_faction_army_list = {
			-- {"medkit_tactical","st_medkit_tactical"},
		-- }
		-- local mc_faction_bandit_list = {
			-- {"medkit_faction_bandit","st_medkit_faction_bandit"},
		-- }
		-- local mc_faction_csky_list = {
			-- {"medkit_faction_clearsky","st_medkit_faction_clearsky"},
		-- }
		-- local mc_faction_dolg_list = {
			-- {"medkit_faction_duty","st_medkit_faction_duty"},
			-- {"medkit_tactical","st_medkit_tactical"},
		-- }
		-- local mc_faction_ecolog_list = {
			-- {"medkit_detox","st_medkit_detox"},
		-- }
		-- local mc_faction_freedom_list = {
			-- {"medkit_faction_freedom","st_medkit_faction_freedom"},
		-- }
		-- local mc_faction_greh_list = {
			-- {"medkit_faction_sin","st_medkit_faction_sin"},
		-- }
		-- local mc_faction_isg_list = {
			-- {"medkit_faction_isg","st_medkit_faction_isg"},
			-- {"medkit_combat","st_medkit_combat"},
		-- }
		-- local mc_faction_killer_list = {
			-- {"medkit_faction_merc","st_medkit_faction_merc"},
			-- {"medkit_combat","st_medkit_combat"},
		-- }
		-- local mc_faction_monolith_list = {
			-- {"medkit_faction_monolith","st_medkit_faction_monolith"},
		-- }
		-- local mc_faction_renegade_list = {
			-- {"medkit_faction_renegade","st_medkit_faction_renegade"},
		-- }
		-- -- local mc_faction_stalker_list = {
		-- -- }
		
		-- table.insert( TB_RF_Receiver_Packages.tb_extraloot, tb_extraloot_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_army, mc_faction_army_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_bandit, mc_faction_bandit_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_csky, mc_faction_csky_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_dolg, mc_faction_dolg_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_ecolog, mc_faction_ecolog_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_freedom, mc_faction_freedom_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_greh, mc_faction_greh_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_isg, mc_faction_isg_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_killer, mc_faction_killer_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_monolith, mc_faction_monolith_list )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_renegade, mc_faction_renegade_list )
		-- -- table.insert( TB_RF_Receiver_Packages.mc_faction_stalker, mc_faction_stalker_list )