if zzz_player_injuries then
  zzz_player_injuries.medkits.civmedkit = {head=3,torso=3,rightleg=1,leftleg=1,rightarm=1,leftarm=1}
  zzz_player_injuries.medkits.tacmedkit = {head=8,torso=9,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.commedkit = {head=1,torso=5,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.toxmedkit = {head=3,torso=3,rightleg=2,leftleg=2,rightarm=2,leftarm=2}
  zzz_player_injuries.medkits.colbandage = {torso=3,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.prebandage = {torso=5,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.bandaids = {rightleg=1,leftleg=1,rightarm=1,leftarm=1}  
  zzz_player_injuries.medkits.rag = {rightarm=1,leftarm=1}

  zzz_player_injuries.healhelp.tacmedkit = {torso=2,rightleg=2,leftleg=2,rightarm=2,leftarm=2}
  zzz_player_injuries.healhelp.commedkit = {head=2,torso=2,rightleg=1,leftleg=1,rightarm=2,leftarm=2}
  zzz_player_injuries.healhelp.toxmedkit = {head=3,torso=3,rightarm=1,leftarm=1}

end