if not TB_RF_Receiver_Packages then
    printf("TB's RF Receiver Hidden Package Sidequests not found. Going back to sleep...")
    return
end

function on_game_start()

	if TB_RF_Receiver_Packages.mc_faction_greh then
		printf("CookBook's QOL - An Uncalled for patch detected. Adding Elixir to Sin's packages...")
		table.insert( TB_RF_Receiver_Packages.mc_faction_greh, {"elixir","st_elixir"} )
	else
		printf("CookBook's QOL - An Uncalled for patch not found. Sin gets nuthin'...")
		return
	end
end