function on_game_start()
    RegisterScriptCallback("on_specific_character_init", function(character_id, data)

	-- we're assuming new modded templates reuse the same classes

	if data.community == ("army") then
		if data.class == ("sim_default_military_0") then
			data.rank_max = "10000"
		elseif data.class == ("sim_default_military_1") then
            data.rank_min = "4000"
            data.rank_max = "28000"
		elseif data.class == ("sim_default_military_2") then
            data.rank_min = "26000"
            data.rank_max = "38000"
		elseif data.class == ("sim_default_military_3") then
            data.rank_min = "31000"
            data.rank_max = "48000"
		elseif data.class == ("sim_default_military_3_default_sniper") then
            data.rank_min = "31000"
            data.rank_max = "48000"
		elseif data.class == ("sim_default_military_4") then
            data.rank_min = "40000"
            data.rank_max = "74000"
		else
			data.rank_min = "32000"
			data.rank_max = "68000"
		end

	elseif data.community == ("bandit") then
		if data.class == ("sim_default_bandit_0") then
            data.rank_min = "1000"
            data.rank_max = "7000"
		elseif data.class == ("sim_default_bandit_1") then
            data.rank_min = "7000"
            data.rank_max = "14000"
		elseif data.class == ("sim_default_bandit_2") then
            data.rank_min = "10000"
            data.rank_max = "18000"
		elseif data.class == ("sim_default_bandit_3") then
            data.rank_min = "16000"
            data.rank_max = "30000"
		elseif data.class == ("sim_default_bandit_4") then
            data.rank_min = "32000"
            data.rank_max = "64000"
		else
			data.rank_min = "42000"
			data.rank_max = "84000"
		end

	elseif data.community == ("csky") then
		if data.class == ("sim_default_csky_0") then
            data.rank_min = "1000"
            data.rank_max = "6000"
		elseif data.class == ("sim_default_csky_1") then
            data.rank_min = "5000"
            data.rank_max = "10000"
		elseif data.class == ("sim_default_csky_2") then
            data.rank_min = "9000"
            data.rank_max = "18000"
		elseif data.class == ("sim_default_csky_3") then
            data.rank_min = "16000"
            data.rank_max = "36000"
		elseif data.class == ("sim_default_csky_4") then
            data.rank_min = "28000"
            data.rank_max = "64000"
		else
			data.rank_min = "30000"
			data.rank_max = "60000"
		end

	elseif data.community == ("duty") then
		if data.class == ("sim_default_duty_0") then
            data.rank_min = "1500"
            data.rank_max = "7000"
		elseif data.class == ("sim_default_duty_1") then
            data.rank_min = "5000"
            data.rank_max = "10000"
		elseif data.class == ("sim_default_duty_2") then
            data.rank_min = "9000"
            data.rank_max = "18000"
		elseif data.class == ("sim_default_duty_3") then
            data.rank_min = "20000"
            data.rank_max = "42000"
		elseif data.class == ("sim_default_duty_4") then
            data.rank_min = "40000"
            data.rank_max = "64000"
		else
			data.rank_min = "24000"
			data.rank_max = "64000"
		end

	elseif data.community == ("ecolog") then
		if data.class == ("sim_default_ecolog_0") then
            data.rank_min = "2000"
            data.rank_max = "10000"
		elseif data.class == ("sim_default_ecolog_01") then
            data.rank_min = "3000"
            data.rank_max = "16000"
		elseif data.class == ("sim_default_ecolog_1") then
            data.rank_min = "5000"
            data.rank_max = "28000"
		elseif data.class == ("sim_default_ecolog_2") then
            data.rank_min = "9000"
            data.rank_max = "35000"
		elseif data.class == ("sim_default_ecolog_3") then
            data.rank_min = "16000"
            data.rank_max = "48000"
		elseif data.class == ("sim_default_ecolog_4") then
            data.rank_min = "22000"
            data.rank_max = "58000"
		elseif data.class == ("sim_default_ecolog_5") then
            data.rank_min = "32000"
            data.rank_max = "74000"
		else
			data.rank_min = "24000"
			data.rank_max = "72000"
		end

	elseif data.community == ("freedom") then
		if data.class == ("sim_default_freedom_0") then
			data.rank_min = "1000"
			data.rank_max = "8000"
		elseif data.class == ("sim_default_freedom_1") then
			data.rank_min = "7000"
			data.rank_max = "15000"
		elseif data.class == ("sim_default_freedom_2") then
			data.rank_min = "15000"
			data.rank_max = "25000"
		elseif data.class == ("sim_default_freedom_3") then
			data.rank_min = "22000"
			data.rank_max = "45000"
		elseif data.class == ("sim_default_freedom_4") then
			data.rank_min = "45000"
			data.rank_max = "68000"
		else
			data.rank_min = "32000"
			data.rank_max = "64000"
		end

	elseif data.community == ("greh") then
		if data.class == ("sim_default_greh_0") then
			data.rank_min = "1000"
			data.rank_max = "6000"
		elseif data.class == ("sim_default_greh_1") then
			data.rank_min = "4000"
			data.rank_max = "10000"
		elseif data.class == ("sim_default_greh_2") then
			data.rank_min = "5000"
			data.rank_max = "18000"
		elseif data.class == ("sim_default_greh_3") then
			data.rank_min = "12000"
			data.rank_max = "28000"
		elseif data.class == ("sim_default_greh_4") then
			data.rank_min = "24000"
			data.rank_max = "64000"
		else
			data.rank_min = "24000"
			data.rank_max = "54000"
		end

	elseif data.community == ("isg") then
		if data.class == ("sim_default_isg_1") then
			data.rank_min = "1000"
			data.rank_max = "5000"
		elseif data.class == ("sim_default_isg_2") then
			data.rank_min = "6000"
			data.rank_max = "14000"
		elseif data.class == ("sim_default_isg_3") then
			data.rank_min = "11000"
			data.rank_max = "20000"
		elseif data.class == ("sim_default_isg_4") then
			data.rank_min = "40000"
			data.rank_max = "74000"
		elseif data.class == ("sim_default_isg_5") then
			data.rank_min = "48000"
			data.rank_max = "89000"
		else
			data.rank_min = "25000"
			data.rank_max = "84000"
		end

	elseif data.community == ("killer") then
		if data.class == ("sim_default_killer_0") then
			data.rank_min = "3000"
			data.rank_max = "9000"
		elseif data.class == ("sim_default_killer_1") then
			data.rank_min = "7000"
			data.rank_max = "16000"
		elseif data.class == ("sim_default_killer_2") then
			data.rank_min = "14000"
			data.rank_max = "24000"
		elseif data.class == ("sim_default_killer_3") then
			data.rank_min = "24000"
			data.rank_max = "79000"
		elseif data.class == ("sim_default_killer_4") then
			data.rank_min = "56000"
			data.rank_max = "82000"
		elseif data.class == ("sim_default_killer_5") then
			-- data.rank_min = "99000"
			-- data.rank_max = "298000"
			data.rank_min = "64000"
			data.rank_max = "92000"
		else
			data.rank_min = "46000"
			-- data.rank_max = "94000"
			data.rank_max = "84000"
		end

	elseif data.community == ("monolith") then
		if data.class == ("sim_default_monolith_0") then
			data.rank_min = "3000"
			data.rank_max = "9000"
		elseif data.class == ("sim_default_monolith_1") then
			data.rank_min = "7000"
			data.rank_max = "25000"
		elseif data.class == ("sim_default_monolith_2") then
			data.rank_min = "12000"
			data.rank_max = "38000"
		elseif data.class == ("sim_default_monolith_3") then
			data.rank_min = "24000"
			data.rank_max = "98000"
		elseif data.class == ("sim_default_monolith_4") then
			data.rank_min = "180000"
			data.rank_max = "1990000"
		else
			data.rank_min = "82000"
			data.rank_max = "38000"
		end

	elseif data.community == ("renegade") then
		if data.class == ("sim_default_renegade_0") then
			data.rank_min = "1000"
			data.rank_max = "8000"
		elseif data.class == ("sim_default_renegade_1") then
			data.rank_min = "8000"
			data.rank_max = "20000"
		elseif data.class == ("sim_default_renegade_2") then
			data.rank_min = "20000"
			data.rank_max = "55000"
		elseif data.class == ("sim_default_renegade_3") then
			data.rank_min = "21000"
			data.rank_max = "59000"
		elseif data.class == ("sim_default_renegade_4") then
			data.rank_min = "37000"
			data.rank_max = "64000"
		else
			data.rank_min = "20000"
			data.rank_max = "55000"
		end

	elseif data.community == ("stalker") then
		if data.class == ("sim_default_stalker_0") then
			data.rank_min = "1000"
			data.rank_max = "8000"
		elseif data.class == ("sim_default_stalker_1") then
			data.rank_min = "8000"
			data.rank_max = "14000"
		elseif data.class == ("sim_default_stalker_2") then
			data.rank_min = "14000"
			data.rank_max = "22000"
		elseif data.class == ("sim_default_stalker_3") then
			data.rank_min = "22000"
			data.rank_max = "40000"
		elseif data.class == ("sim_default_stalker_4") then
			-- data.rank_min = "175000"
			-- data.rank_max = "840000"
			data.rank_min = "40000"
			data.rank_max = "64000"
		else
			data.rank_min = "35000"
			data.rank_max = "64000"
		end

	elseif data.community == ("zombied") then
		if data.class == ("sim_default_zombied_0") then
			data.rank_min = "1000"
			data.rank_max = "5000"
		elseif data.class == ("sim_default_zombied_1") then
			data.rank_min = "5000"
			data.rank_max = "9000"
		elseif data.class == ("sim_default_zombied_2") then
			data.rank_min = "9000"
			data.rank_max = "20000"
		elseif data.class == ("sim_default_freedom_3") then
			data.rank_min = "20000"
			data.rank_max = "36000"
		elseif data.class == ("sim_default_freedom_4") then
			data.rank_min = "32000"
			data.rank_max = "50000"
		else
			data.rank_min = "32000"
			data.rank_max = "64000"
		end

	end
    end)
end
