if zzz_player_injuries then
  zzz_player_injuries.medkits.medkit_civilian = {head=3,torso=3,rightleg=1,leftleg=1,rightarm=1,leftarm=1}
  zzz_player_injuries.medkits.medkit_tactical = {head=8,torso=9,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.medkit_combat = {head=1,torso=5,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.medkit_detox = {head=3,torso=3,rightleg=2,leftleg=2,rightarm=2,leftarm=2}
  zzz_player_injuries.medkits.bandage_cooling = {torso=3,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.bandage_presure = {torso=5,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.bandage_bandaids = {rightleg=1,leftleg=1,rightarm=1,leftarm=1}  
  zzz_player_injuries.medkits.bandage_rag = {rightarm=1,leftarm=1}  
  
  zzz_player_injuries.medkits.paracetamol = {head=1,torso=2,rightleg=2,leftleg=2,rightarm=2,leftarm=2}
  zzz_player_injuries.medkits.tramadol = {head=2,torso=3,rightleg=3,leftleg=3,rightarm=3,leftarm=3}
  zzz_player_injuries.medkits.active_charcoal = {head=1}
  zzz_player_injuries.medkits.multivitamin = {torso=1}
  zzz_player_injuries.medkits.iodine = {head=2,torso=3}
  
  zzz_player_injuries.medkits.medkit_faction_bandit = {head=2,torso=3,rightleg=2,leftleg=2,rightarm=1,leftarm=1}
  zzz_player_injuries.medkits.medkit_faction_duty = {head=8,torso=9,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.medkit_faction_freedom = {head=5,torso=6,rightleg=3,leftleg=3,rightarm=3,leftarm=3}
  zzz_player_injuries.medkits.medkit_faction_isg = {head=10,torso=10,rightleg=5,leftleg=5,rightarm=5,leftarm=5}
  zzz_player_injuries.medkits.medkit_faction_monolith = {head=5,torso=7,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.medkit_faction_merc = {head=7,torso=8,rightleg=4,leftleg=4,rightarm=4,leftarm=4}
  zzz_player_injuries.medkits.medkit_faction_clearsky = {head=5,torso=5,rightleg=2,leftleg=2,rightarm=2,leftarm=2}
  zzz_player_injuries.medkits.medkit_faction_sin = {head=2,torso=3,rightleg=2,leftleg=2,rightarm=1,leftarm=1}
  zzz_player_injuries.medkits.medkit_faction_renegade = {head=2,torso=3,rightleg=2,leftleg=2,rightarm=1,leftarm=1}
  zzz_player_injuries.medkits.medkit_spongebob = {head=10,torso=10,rightleg=5,leftleg=5,rightarm=5,leftarm=5}
  
  zzz_player_injuries.healhelp.medkit_tactical = {torso=2,rightleg=2,leftleg=2,rightarm=2,leftarm=2}
  zzz_player_injuries.healhelp.medkit_combat = {head=2,torso=2,rightleg=1,leftleg=1,rightarm=2,leftarm=2}
  zzz_player_injuries.healhelp.medkit_detox = {head=3,torso=3,rightarm=1,leftarm=1}
  
  zzz_player_injuries.healhelp.tramadol = {head=2,rightleg=1,leftleg=1,rightarm=1,leftarm=1}
  zzz_player_injuries.healhelp.paracetamol = {head=1,rightarm=1,leftarm=1}
  zzz_player_injuries.healhelp.active_charcoal = {head=1}
 
  zzz_player_injuries.healhelp.medkit_faction_merc = {torso=2,rightleg=2,leftleg=2,rightarm=3,leftarm=3}
  zzz_player_injuries.healhelp.medkit_faction_duty = {torso=2,rightleg=2,leftleg=2,rightarm=3,leftarm=3}
  zzz_player_injuries.healhelp.medkit_faction_monolith = {rightleg=1,leftleg=1,rightarm=2,leftarm=2}
  zzz_player_injuries.healhelp.medkit_faction_isg = {head=3,torso=5,rightleg=2,leftleg=2,rightarm=3,leftarm=3}
  zzz_player_injuries.healhelp.medkit_faction_freedom = {rightleg=1,leftleg=1,rightarm=1,leftarm=1}
  zzz_player_injuries.healhelp.medkit_spongebob = {rightleg=5,leftleg=5,rightarm=5,leftarm=5}
end