--[[
        Emptiable Canteens (for Fillable Canteens 2.0)

        Author: Singustromo
        Last edited: 2024-10-03

        This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
--]]

parent = haruka_fill
sound_objs = {
        empty_flask = sound_object("fillable_canteens\\empty_flask"),
}

function empty(obj, sec)
        alife_create_item("empty_canteen", obj:parent())
        sound_objs.empty_flask:play(db.actor, 0, sound_object.s2d)
        alife_release(obj)
end

function empty_condition_function(obj, bag, mode)
        local p = obj:parent()
        if not (p and p:id() == AC_ID) then return end

        local sec = obj:section()
        if (sec ~= "empty_canteen" and parent.waters[sec]) then
                return true
        end
end

function on_game_start()
        assert(parent, game.translate_string("st_haruka_empty_flask_notice_prerequisite"))

        add_functor = custom_functor_autoinject.add_functor
        add_functor("haruka_empty_flask", empty_condition_function, function() 
                return game.translate_string("st_haruka_empty_flask")
        end, nil, empty)
end
