function on_game_start()

	if TB_RF_Receiver_Packages.tb_extraloot then
		if TB_RF_Receiver_Packages.mc_faction_bandit then
			table.insert( TB_RF_Receiver_Packages.mc_faction_bandit, {"banditmedkit","st_banditmedkit"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_csky, {"clearskymedkit","st_clearskymedkit"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_dolg, {"dutymedkit","st_dutymedkit"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_freedom, {"freedommedkit","st_freedommedkit"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_greh, {"sinmedkit","st_sinmedkit"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_isg, {"isgmedkit","st_isgmedkit"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_killer, {"mercmedkit","st_mercmedkit"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_monolith, {"monolithmedkit","st_monolithmedkit"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_renegade, {"renegademedkit","st_renegademedkit"} )
			-- table.insert( TB_RF_Receiver_Packages.mc_faction_stalker,  )

		end
	end
end