function on_game_start()
    RegisterScriptCallback("on_specific_character_init", function(character_id, data)

	-- we're assuming new modded templates reuse the same classes

	if data.community == ("army") then
		if data.class == ("sim_default_military_0") then
			data.rank_max = "10000"
		elseif data.class == ("sim_default_military_1") then
            data.rank_min = "2000"
            data.rank_max = "18000"
		elseif data.class == ("sim_default_military_2") then
            data.rank_min = "16000"
            data.rank_max = "28000"
		elseif data.class == ("sim_default_military_3") then
            data.rank_min = "21000"
            data.rank_max = "38000"
		elseif data.class == ("sim_default_military_3_default_sniper") then
            data.rank	= "472"
		elseif data.class == ("sim_default_military_4") then
            data.rank_min = "30000"
            data.rank_max = "64000"
			--vanilla wise, only special traders are left here
			-- mod wise... *shrug*
		-- elseif data.class == ("sim_default_military_trader") then
            -- data.rank_min = "32000"
            -- data.rank_max = "60000"
		-- elseif data.class == ("sim_default_military_mechanic") then
			-- data.rank_min = "32000"
			-- data.rank_max = "64000"
		-- elseif data.class == ("sim_default_military_medic") then
			-- data.rank_min = "32000"
			-- data.rank_max = "64000"
		-- elseif data.class == ("sim_default_military_barman") then
			-- data.rank_min = "32000"
			-- data.rank_max = "64000"
		elseif data.class == ("sim_default_military_dead_default_0") then
            data.rank	= "597"
		elseif data.class == ("sim_default_military_dead_default_1") then
            data.rank	= "615"
		elseif data.class == ("sim_default_military_dead_default_2") then
            data.rank	= "688"
		elseif data.class == ("sim_default_military_dead_default_3") then
            data.rank	= "396"
		else
			data.rank_min = "32000"
			data.rank_max = "64000"
		end

	elseif data.community == ("bandit") then
		if data.class == ("sim_default_bandit_0") then
            data.rank_min = "1000"
            data.rank_max = "7000"
		elseif data.class == ("sim_default_bandit_1") then
            data.rank_min = "7000"
            data.rank_max = "12000"
		elseif data.class == ("sim_default_bandit_2") then
            data.rank_min = "10000"
            data.rank_max = "18000"
		elseif data.class == ("sim_default_bandit_3") then
            data.rank_min = "16000"
            data.rank_max = "30000"
		elseif data.class == ("sim_default_bandit_4") then
            data.rank_min = "30000"
            data.rank_max = "64000"
		elseif data.class == ("sim_default_bandit_dead_default_0") then
            data.rank	= "364"
		elseif data.class == ("sim_default_bandit_dead_default_1") then
            data.rank	= "604"
		elseif data.class == ("sim_default_bandit_dead_default_2") then
            data.rank	= "606"
		elseif data.class == ("sim_default_bandit_dead_default_3") then
            data.rank	= "359"
		else
			data.rank_min = "32000"
			data.rank_max = "64000"
		end

	elseif data.community == ("csky") then
		if data.class == ("sim_default_csky_0") then
            data.rank_min = "1000"
            data.rank_max = "6000"
		elseif data.class == ("sim_default_csky_1") then
            data.rank_min = "5000"
            data.rank_max = "10000"
		elseif data.class == ("sim_default_csky_2") then
            data.rank_min = "9000"
            data.rank_max = "18000"
		elseif data.class == ("sim_default_csky_3") then
            data.rank_min = "16000"
            data.rank_max = "36000"
		elseif data.class == ("sim_default_csky_4") then
            data.rank_min = "28000"
            data.rank_max = "64000"
		else
			data.rank_min = "32000"
			data.rank_max = "64000"
		end

	elseif data.community == ("duty") then
		if data.class == ("sim_default_duty_0") then
            data.rank_min = "1500"
            data.rank_max = "7000"
		elseif data.class == ("sim_default_duty_1") then
            data.rank_min = "5000"
            data.rank_max = "10000"
		elseif data.class == ("sim_default_duty_2") then
            data.rank_min = "9000"
            data.rank_max = "18000"
		elseif data.class == ("sim_default_duty_3") then
            data.rank_min = "20000"
            data.rank_max = "42000"
		elseif data.class == ("sim_default_duty_4") then
            data.rank_min = "40000"
            data.rank_max = "64000"
		else
			data.rank_min = "32000"
			data.rank_max = "64000"
		end

	elseif data.community == ("ecolog") then
		if data.class == ("sim_default_ecolog_0") then
            data.rank_min = "2000"
            data.rank_max = "10000"
		elseif data.class == ("sim_default_ecolog_01") then
            data.rank_min = "3000"
            data.rank_max = "14000"
		elseif data.class == ("sim_default_ecolog_1") then
            data.rank_min = "5000"
            data.rank_max = "24000"
		elseif data.class == ("sim_default_ecolog_2") then
            data.rank_min = "9000"
            data.rank_max = "24000"
		elseif data.class == ("sim_default_ecolog_3") then
            data.rank_min = "16000"
            data.rank_max = "40000"
		elseif data.class == ("sim_default_ecolog_4") then
            data.rank_min = "22000"
            data.rank_max = "44000"
		elseif data.class == ("sim_default_ecolog_5") then
            data.rank_min = "32000"
            data.rank_max = "64000"
		else
			data.rank_min = "32000"
			data.rank_max = "64000"
		end

	elseif data.community == ("freedom") then
		if data.class == ("sim_default_freedom_0") then
			data.rank_min = "1000"
			data.rank_max = "3000"
		elseif data.class == ("sim_default_freedom_1") then
			data.rank_min = "7000"
			data.rank_max = "15000"
		elseif data.class == ("sim_default_freedom_2") then
			data.rank_min = "15000"
			data.rank_max = "25000"
		elseif data.class == ("sim_default_freedom_3") then
			data.rank_min = "22000"
			data.rank_max = "45000"
		elseif data.class == ("sim_default_freedom_4") then
			data.rank_min = "45000"
			data.rank_max = "64000"
		else
			data.rank_min = "32000"
			data.rank_max = "64000"
		end

	elseif data.community == ("greh") then
		if data.class == ("sim_default_greh_0") then
			data.rank_min = "1000"
			data.rank_max = "6000"
		elseif data.class == ("sim_default_greh_1") then
			data.rank_min = "4000"
			data.rank_max = "10000"
		elseif data.class == ("sim_default_greh_2") then
			data.rank_min = "5000"
			data.rank_max = "18000"
		elseif data.class == ("sim_default_greh_3") then
			data.rank_min = "12000"
			data.rank_max = "28000"
		elseif data.class == ("sim_default_greh_4") then
			data.rank_min = "24000"
			data.rank_max = "52000"
		else
			data.rank_min = "32000"
			data.rank_max = "50000"
		end

	elseif data.community == ("isg") then
		if data.class == ("sim_default_isg_1") then
			data.rank_min = "1000"
			data.rank_max = "3000"
		elseif data.class == ("sim_default_isg_2") then
			data.rank_min = "1500"
			data.rank_max = "3500"
		elseif data.class == ("sim_default_isg_3") then
			data.rank_min = "2500"
			data.rank_max = "5000"
		elseif data.class == ("sim_default_isg_4") then
			data.rank_min = "40000"
			data.rank_max = "64000"
		else
			data.rank_min = "25000"
			data.rank_max = "50000"
		end

	elseif data.community == ("killer") then
		if data.class == ("sim_default_killer_0") then
			data.rank_min = "1000"
			data.rank_max = "3000"
		elseif data.class == ("sim_default_killer_1") then
			data.rank_min = "7000"
			data.rank_max = "16000"
		elseif data.class == ("sim_default_killer_2") then
			data.rank_min = "14000"
			data.rank_max = "24000"
		elseif data.class == ("sim_default_killer_3") then
			data.rank_min = "24000"
			data.rank_max = "39000"
		elseif data.class == ("sim_default_killer_4") then
			data.rank_min = "39000"
			data.rank_max = "61000"
		else
			data.rank_min = "30000"
			data.rank_max = "60000"
		end

	elseif data.community == ("monolith") then
		if data.class == ("sim_default_monolith_0") then
			data.rank_min = "3000"
			data.rank_max = "7000"
		elseif data.class == ("sim_default_monolith_1") then
			data.rank_min = "7000"
			data.rank_max = "12000"
		elseif data.class == ("sim_default_monolith_2") then
			data.rank_min = "12000"
			data.rank_max = "24000"
		elseif data.class == ("sim_default_monolith_3") then
			data.rank_min = "24000"
			data.rank_max = "44000"
		elseif data.class == ("sim_default_monolith_4") then
			data.rank_min = "40000"
			data.rank_max = "65000"
		elseif data.class == ("sim_monolith_sniper") then
            data.rank	= "386"
		elseif data.class == ("sim_monolith_specnaz_rg6") then
            data.rank	= "669"
		elseif data.class == ("sim_monolith_sniper_gauss") then
            data.rank	= "382"
		elseif data.class == ("sim_default_monolith_dead_default_0") then
            data.rank	= "541"
		elseif data.class == ("sim_default_monolith_dead_default_1") then
            data.rank	= "664"
		elseif data.class == ("sim_default_monolith_dead_default_2") then
            data.rank	= "591"
		elseif data.class == ("sim_default_monolith_dead_default_3") then
            data.rank	= "729"
		else
			data.rank_min = "35000"
			data.rank_max = "64000"
		end

	elseif data.community == ("renegade") then
		if data.class == ("sim_default_renegade_0") then
			data.rank_min = "1000"
			data.rank_max = "8000"
		elseif data.class == ("sim_default_renegade_1") then
			data.rank_min = "8000"
			data.rank_max = "20000"
		elseif data.class == ("sim_default_renegade_2") then
			data.rank_min = "20000"
			data.rank_max = "35000"
		else
			data.rank_min = "20000"
			data.rank_max = "65000"
		end

	elseif data.community == ("stalker") then
		if data.class == ("sim_default_stalker_0") then
			data.rank_min = "1000"
			data.rank_max = "8000"
		elseif data.class == ("sim_default_stalker_1") then
			data.rank_min = "1000"
			data.rank_max = "3000"
		elseif data.class == ("sim_default_stalker_2") then
			data.rank_min = "14000"
			data.rank_max = "22000"
		elseif data.class == ("sim_default_stalker_3") then
			data.rank_min = "22000"
			data.rank_max = "40000"
		elseif data.class == ("sim_default_stalker_4") then
			data.rank_min = "40000"
			data.rank_max = "64000"
		else
			data.rank_min = "35000"
			data.rank_max = "64000"
		end

	elseif data.community == ("zombied") then
		if data.class == ("sim_default_zombied_0") then
			data.rank_min = "900"
			data.rank_max = "9000"
		elseif data.class == ("sim_default_zombied_1") then
			data.rank_min = "9000"
			data.rank_max = "20000"
		elseif data.class == ("sim_default_zombied_2") then
			data.rank_min = "20000"
			data.rank_max = "36000"
		elseif data.class == ("sim_default_freedom_3") then
			data.rank_min = "32000"
			data.rank_max = "50000"
		else
			data.rank_min = "32000"
			data.rank_max = "64000"
		end

	end
    end)
end
