local function patch_tbrfpackage_tables()
    if not tb_extraloot then
        return false
    end

    if tb_extraloot then
		tb_extraloot{"bandage_aloe","st_bandage_aloe"}
    end
    
    return true
end

if not patch_tbrfpackage_tables() then
    CreateTimeEvent("tbrfpackage_patch", "wait_for_tables", 1.0, function()
        if patch_tbrfpackage_tables() then
            return true
        end
        return false
    end)
end

local original_on_game_start = on_game_start
function on_game_start()
    if original_on_game_start then
        original_on_game_start()
    end
    patch_tbrfpackage_tables()
end