function on_game_start()
    RegisterScriptCallback("on_specific_character_init", function(character_id, data)

	if data.community == ("csky") then
		if data.class == ("sim_default_csky_0") then
            data.name = "GENERATE_NAME_csky"
		elseif data.class == ("sim_default_csky_1") then
            data.name = "GENERATE_NAME_csky"
		elseif data.class == ("sim_default_csky_2") then
            data.name = "GENERATE_NAME_csky"
		elseif data.class == ("sim_default_csky_3") then
            data.name = "GENERATE_NAME_csky"
		end
	elseif data.community == ("ecolog") then
		if data.class == ("sim_default_ecolog_0") then
            data.name = "GENERATE_NAME_science"
		elseif data.class == ("sim_default_ecolog_01") then
            data.name = "GENERATE_NAME_science"
		-- elseif data.class == ("sim_default_ecolog_1") then
		elseif data.class == ("sim_default_ecolog_2") then
            data.name = "GENERATE_NAME_stalker"
		elseif data.class == ("sim_default_ecolog_3") then
            data.name = "GENERATE_NAME_guard"
		elseif data.class == ("sim_default_ecolog_4") then
            data.name = "GENERATE_NAME_guard"
		elseif data.class == ("sim_default_ecolog_5") then
            data.name = "GENERATE_NAME_officer"
		end
	elseif data.community == ("greh") then
		if data.class == ("sim_default_greh_0") then
            data.name = "GENERATE_NAME_sinner"
		elseif data.class == ("sim_default_greh_1") then
            data.name = "GENERATE_NAME_sinner"
		elseif data.class == ("sim_default_greh_2") then
            data.name = "GENERATE_NAME_sinner"
		elseif data.class == ("sim_default_greh_3") then
            data.name = "GENERATE_NAME_sinner"
		elseif data.class == ("sim_default_greh_4") then
            data.name = "GENERATE_NAME_sinner"
		end
	elseif data.community == ("isg") then
		if data.class == ("sim_default_isg_0") then
            data.name = "GENERATE_NAME_isg_private"
		elseif data.class == ("sim_default_isg_1") then
            data.name = "GENERATE_NAME_isg_private"
		elseif data.class == ("sim_default_isg_2") then
            data.name = "GENERATE_NAME_isg_sergeant"
		elseif data.class == ("sim_default_isg_3") then
            data.name = "GENERATE_NAME_isg_sergeant"
		elseif data.class == ("sim_default_isg_4") then
            data.name = "GENERATE_NAME_isg_lieutenant"
		elseif data.class == ("sim_default_isg_5") then
            data.name = "GENERATE_NAME_isg_captain"
		end
	elseif data.community == ("killer") then
		if data.class == ("sim_default_killer_0") then
            data.name = "GENERATE_NAME_merc"
		elseif data.class == ("sim_default_killer_1") then
            data.name = "GENERATE_NAME_merc"
		elseif data.class == ("sim_default_killer_2") then
            data.name = "GENERATE_NAME_merc"
		elseif data.class == ("sim_default_killer_3") then
            data.name = "GENERATE_NAME_merc"
		elseif data.class == ("sim_default_killer_4") then
            data.name = "GENERATE_NAME_merc"
		end
	elseif data.community == ("monolith") then
		if data.class == ("sim_default_monolith_0") then
            data.name = "GENERATE_NAME_monobot"
		elseif data.class == ("sim_default_monolith_1") then
            data.name = "GENERATE_NAME_monobot"
		elseif data.class == ("sim_default_monolith_2") then
            data.name = "GENERATE_NAME_monolow"
		elseif data.class == ("sim_default_monolith_3") then
            data.name = "GENERATE_NAME_monohigh"
		elseif data.class == ("sim_default_monolith_4") then
            data.name = "GENERATE_NAME_monotop"
		end
	elseif data.community == ("renegade") then
		if data.class == ("sim_default_renegade_0") then
            data.name = "GENERATE_NAME_renegade"
		elseif data.class == ("sim_default_renegade_1") then
            data.name = "GENERATE_NAME_renegade"
		elseif data.class == ("sim_default_renegade_2") then
            data.name = "GENERATE_NAME_renegade"
		elseif data.class == ("sim_default_renegade_3") then
            data.name = "GENERATE_NAME_renegade"
		elseif data.class == ("sim_default_renegade_4") then
            data.name = "GENERATE_NAME_renegade"
		end
	end

    end)
end