if not spatial_anomalies then
    printf("Spatial Anomalies not found. Going back to sleep...")
    return
end

function on_game_start()
    RegisterScriptCallback("on_specific_character_dialog_list", function(character_id, dialog_list)

        if character_id == "zat_b18_noah" then
            local res = dialog_list:add("ask_about_compass")

            if res then
                printf("adding dialog %s for %s, pos %s", "ask_about_compass", character_id, res)
            end
        end
    end)
end