function on_game_start()
    local bandages = axr_otheal.bandages
    local medkits = axr_otheal.medkits
	
    if bandages then
		-- -- New Medkits and Bandages
        bandages["bandage_cooling"] = true
        bandages["bandage_presure"] = true
        bandages["bandage_rag"] = true
        bandages["bandage_bandaids"] = true
    end
	if medkits then
		-- -- New Medkits and Bandages
        medkits["medkit_civilian"] = true
        medkits["medkit_tactical"] = true
    end
end