function on_game_start()


	if TB_RF_Receiver_Packages.tb_extraloot then

		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"medkit_civilian","st_medkit_civilian"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"bandage_cooling","st_bandage_cooling"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"bandage_presure","st_bandage_presure"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_army, {"medkit_tactical","st_medkit_tactical"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_dolg, {"medkit_tactical","st_medkit_tactical"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_ecolog, {"medkit_detox","st_medkit_detox"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_isg, {"medkit_combat","st_medkit_combat"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_killer, {"medkit_combat","st_medkit_combat"} )
		-- table.insert( TB_RF_Receiver_Packages.mc_faction_stalker,  )

	end
end