if not TB_RF_Receiver_Packages then
    printf("TB's RF Receiver Hidden Package Sidequests not found. Going back to sleep...")
    return
end

function on_game_start()

	if TB_RF_Receiver_Packages.mc_faction_army then
			printf("CookBook's QOL - An Uncalled for patch detected. Making extended changes...")
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"civmedkit","st_civmedkit"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"colbandage","st_colbandage"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"prebandage","st_prebandage"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_army, {"tacmedkit","st_tacmedkit"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_dolg, {"tacmedkit","st_tacmedkit"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_ecolog, {"toxmedkit","st_toxmedkit"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_isg, {"commedkit","st_commedkit"} )
		table.insert( TB_RF_Receiver_Packages.mc_faction_killer, {"commedkit","st_commedkit"} )
		
	elseif TB_RF_Receiver_Packages.tb_extraloot then
			printf("CookBook's QOL - An Uncalled for patch not found. Making default changes...")
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"civmedkit","st_civmedkit"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"colbandage","st_colbandage"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"prebandage","st_prebandage"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"tacmedkit","st_tacmedkit"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"toxmedkit","st_toxmedkit"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraloot, {"commedkit","st_commedkit"} )
	end
end