if zzz_player_injuries then
  zzz_player_injuries.medkits.paracetamol = {head=1,torso=2,rightleg=2,leftleg=2,rightarm=2,leftarm=2}
  zzz_player_injuries.medkits.tramadol = {head=2,torso=3,rightleg=3,leftleg=3,rightarm=3,leftarm=3}
  zzz_player_injuries.medkits.active_charcoal = {head=1}
  zzz_player_injuries.medkits.multivitamin = {torso=1}
  zzz_player_injuries.medkits.iodine = {head=2,torso=3}

  zzz_player_injuries.healhelp.tramadol = {head=2,rightleg=1,leftleg=1,rightarm=1,leftarm=1}
  zzz_player_injuries.healhelp.paracetamol = {head=1,rightarm=1,leftarm=1}
  zzz_player_injuries.healhelp.active_charcoal = {head=1}
end