function on_game_start()

	if TB_RF_Receiver_Packages.tb_extraupgrades then
		-- first we add the basic upgrades
		table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"paintkit_novice","st_paintkit_novice"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"paintkit_sunrise","st_paintkit_sunrise"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"paintkit_trenchcoat","st_paintkit_trenchcoat"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"gunkit_paint","st_paintkit_gunkit_paint"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"gunkit_gunsmith","st_paintkit_gunkit_gunsmith"} )
		table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"gunkit_replace","st_paintkit_gunkit_replace"} )
	
		table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_novice","st_paintkit_novice"} )
		table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_sunrise","st_paintkit_sunrise"} )
		table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_trenchcoat","st_paintkit_trenchcoat"} )
		table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"gunkit_paint","st_paintkit_gunkit_paint"} )
		table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"gunkit_gunsmith","st_paintkit_gunkit_gunsmith"} )
		table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"gunkit_replace","st_paintkit_gunkit_replace"} )
	
		-- then check first if the Uncalled version of the script is being used. If so, populate all new faction tables
		if TB_RF_Receiver_Packages.tb_extraupgrades_up then
	
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades_up, {"paintkit_skat","st_paintkit_skat"} )
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades_up, {"paintkit_exo","st_paintkit_exo"} )
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades_up, {"paintkit_nosorog","st_paintkit_noso"} )
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades_up, {"paintkit_seva","st_paintkit_seva"} )
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades_up, {"gunkit_custom","st_paintkit_gunkit_custom"} )
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades_up, {"gunkit_scope","st_paintkit_gunkit_scope"} )
			
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_skat","st_paintkit_skat"} )
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_exo","st_paintkit_exo"} )
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_nosorog","st_paintkit_noso"} )
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_seva","st_paintkit_seva"} )
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"gunkit_custom","st_paintkit_gunkit_custom"} )
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"gunkit_scope","st_paintkit_gunkit_scope"} )
			
			table.insert( TB_RF_Receiver_Packages.mc_faction_csky, {"paintkit_ace","st_paintkit_ace"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_csky, {"gunkit_cs","st_paintkit_gunkit_cs"} )
			
			table.insert( TB_RF_Receiver_Packages.mc_faction_dolg, {"paintkit_duty_ps5","st_paintkit_dooty"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_dolg, {"gunkit_duty","st_paintkit_gunkit_duty"} )
			
			table.insert( TB_RF_Receiver_Packages.mc_faction_ecolog, {"paintkit_eco_ssp","st_paintkit_eco"} )
			
			table.insert( TB_RF_Receiver_Packages.mc_faction_freedom, {"gunkit_freedom","st_paintkit_gunkit_freedom"} )
			
			table.insert( TB_RF_Receiver_Packages.mc_faction_killer, {"paintkit_merc_lcs","st_paintkit_lcs"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_killer, {"paintkit_merc_tactical","st_paintkit_merc_tactical"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_killer, {"paintkit_ace","st_paintkit_ace"} )
			table.insert( TB_RF_Receiver_Packages.mc_faction_killer, {"gunkit_merc","st_paintkit_gunkit_merc"} )
			
			table.insert( TB_RF_Receiver_Packages.mc_faction_monolith, {"gunkit_mono","st_paintkit_gunkit_mono"} )
			
			table.insert( TB_RF_Receiver_Packages.mc_faction_stalker, {"gunkit_loner","st_paintkit_gunkit_loner"} )
	
		else
			--if it's TB's or Aeonera's versions, only finish the basic tables		
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"paintkit_skat","st_paintkit_skat"} )
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"paintkit_exo","st_paintkit_exo"} )
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"paintkit_nosorog","st_paintkit_noso"} )
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"paintkit_seva","st_paintkit_seva"} )
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"gunkit_custom","st_paintkit_gunkit_custom"} )
			table.insert( TB_RF_Receiver_Packages.tb_extraupgrades, {"gunkit_scope","st_paintkit_gunkit_scope"} )
			
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_seva","st_paintkit_seva"} )
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_skat","st_paintkit_skat"} )
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_exo","st_paintkit_exo"} )
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"paintkit_nosorog","st_paintkit_noso"} )
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"gunkit_custom","st_paintkit_gunkit_custom"} )
			table.insert( TB_RF_Receiver_Packages.CB_streamlined_extraupgrades, {"gunkit_scope","st_paintkit_gunkit_scope"} )
	
		end
	end
end
