if dialogs_devushka_fix then
    detected_less_infuriating_hip = true
	printf("Less Infuriating Hip detected. Making extended changes...")
end

function on_game_start()
    RegisterScriptCallback("on_specific_character_init", function(character_id, data)

        if character_id == "esc_2_12_stalker_fanat" then
			data.supplies= [[
			[spawn] \n
			wpn_binoc \n
			wpn_pmm \n
			ammo_9x18_fmj = 3 \n
			wpn_ak74u_camo_kobra = 1 \n
			ammo_5.45x39_fmj = 3 \n
			#include "gameplay\supplies\character_items_nd.xml"
			#include "gameplay\supplies\character_food.xml"
			#include "gameplay\supplies\character_drugs_3.xml"
			]]
        end
			
        if character_id == "devushka" then
			if less_infuriating_hip == true then
				data.supplies= [[
					[spawn] \n
					wpn_hpsa_alt \n
					ammo_9x19_fmj = 3 \n
					wpn_m4a1_freedom_ac10632 = 1 \n
					ammo_5.56x45_ap = 3 \n
					af_dummy_battery \n
					#include "gameplay\supplies\character_items.xml"
					#include "gameplay\supplies\character_food.xml"
					#include "gameplay\supplies\character_drugs_2.xml"
					]]
			else
				data.supplies= [[
					[spawn] \n
					wpn_hpsa_alt \n
					ammo_9x19_fmj = 3 \n
					wpn_m4a1_freedom_ac10632 = 1 \n
					ammo_5.56x45_ap = 3 \n
					#include "gameplay\supplies\character_items.xml"
					#include "gameplay\supplies\character_food.xml"
					#include "gameplay\supplies\character_drugs_2.xml"
					]]
			end
        end

        if character_id == "esc_smart_terrain_5_7_loner_mechanic_stalker" then
			data.supplies= [[
			[spawn] \n
			wpn_fort500  \n
			ammo_12x76_zhekan = 1 \n
			wpn_fort \n
			ammo_9x18_fmj = 1 \n
			#include "gameplay\supplies\character_items.xml"
			#include "gameplay\supplies\character_food.xml"
			#include "gameplay\supplies\character_drugs_2.xml"
			]]
        end

    end)
end