-- Hip dialog reworked
--====================< Preconditions >====================--
function devushka_medicine_ai1()
	if db.actor:object("medkit_ai1") then
		return true
	end
	return false
end

function devushka_medicine_ai2()
	if db.actor:object("medkit_ai2") then
		return true
	end
	return false
end

function devushka_medicine_ai3()
	if db.actor:object("medkit_ai3") then
		return true
	end
	return false
end

function devushka_basic_toolkit()
	if db.actor:object("itm_basickit") then
		return true
	end
	return false
end

function devushka_delivery_cold()
	local cnt = utils_item.get_amount(db.actor, "device_weather_radar")
    if (cnt >= 2) then
        return true
    end
    return false
end

--====================< Functions >====================--
function give_task_devushka_medicine()
--	dialogs_devushka_fix.give_task('devushka_fixed_medicine')
	task_manager.get_task_manager():give_task("devushka_fixed_medicine")
end

function give_task_devushka_tools()
--	dialogs_devushka_fix.give_task('devushka_fixed_tools')
	task_manager.get_task_manager():give_task("devushka_fixed_tools")
end

function devushka_remove_ai1(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "medkit_ai1")
end

function devushka_remove_ai2(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "medkit_ai2")
end

function devushka_remove_ai3(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "medkit_ai3")
end

function devushka_remove_tools(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "itm_basickit")
end

function devushka_medicine_reward_tier2(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "af_dummy_battery", "in", 1) 
	dialogs.relocate_item_section(second_speaker, "stimpack_army", "in", 2) 
	dialogs.relocate_item_section(second_speaker, "morphine", "in", 2) 
--	alife_create_item("af_dummy_battery", db.actor)
--	alife_create_item("stimpack_army", db.actor)
--	alife_create_item("morphine", db.actor)
end

function devushka_medicine_reward_tier3(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "af_dummy_battery", "in", 1) 
	dialogs.relocate_item_section(second_speaker, "medkit_scientic", "in", 3) 
	dialogs.relocate_item_section(second_speaker, "af_kevlar_up", "in", 1) 
--	alife_create_item("af_dummy_battery", db.actor)
--	alife_create_item("medkit_scientic", db.actor)
--	alife_create_item("af_kevlar_up", db.actor)
end

function devushka_cold_delivery_start(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "device_weather_radar", "in", 2) 
	task_manager.get_task_manager():give_task("devushka_fixed_delivery")
end

function devushka_cold_delivery_reward(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "device_weather_radar", 2)
	dialogs.relocate_item_section(second_speaker, "medkit_ai1", "in", 1) 
	dialogs.relocate_item_section(second_speaker, "beer", "in", 1) 
end